### ISSUE TITLE
Task "Crawler Run Multi Process" not compatible with composer Installation

### ISSUE THREAD

**Issue by tjeske2017** [AOEpeople/crawler#308] opened 2018-06-25 13:36 UTC
The task "Crawler Run Multi Process" is not compatible with an composer installation. I think the reason is, the line `$cliPart = '/typo3/cli_dispatch.phpsh crawler';` in public/typo3conf/ext/crawler/Classes/Service/ProcessService.php

In a newer composer installation is no cli_dispatch.phpsh available. Recommended is to use the typo3 console.

**Comment by tomasnorre** [comment] 2018-06-25 15:57
@tjeske2017 We will look into this, this sounds like a mistake. But we haven't seen any problems our self with compose mode.. We have been using it in composer mode since "forever".

Can you please provide us with TYPO3 Version and Crawler version? Thanks.

**Comment by tjeske2017** [comment] 2018-06-26 07:14
Yes sorry. TYPO3 Version 8.7.16 and Crawler Version 6.1.2.
As I mentioned above, I think the problem is, that the file typo3/cli_dispatch.phpsh is needed, which is not present in this config, because here are only a few core extensions and not the whole core. 

To test it I create a simple crawler configuration, a queue task and a multi process task. If I execute the multi process task in the backend the queue will not be processed. With a normal crawler run task it works. I found out that the multi process task works with the package `pagemachine/typo3-composer-legacy-cli`. At least in the backend...
But be carefull: the mentioned package lay down the file cli_dispatch.phpsh in the public/typo3 directory.  If you remove this package the file will be still there and have to delete manually.

here is my composer.json:
{
	"repositories": [
		{ "type": "composer", "url": "https://composer.typo3.org/" }
	],
	"name": "typo3/cms-base-distribution",
	"description" : "TYPO3 CMS Base Distribution",
	"license": "GPL-2.0-or-later",
	"require": {
		"helhum/typo3-console": "^4.9.3 || ^5.2",
		"typo3/cms-about": "^8.7.10",
		"typo3/cms-belog": "^8.7.10",
		"typo3/cms-beuser": "^8.7.10",
		"typo3/cms-context-help": "^8.7.10",
		"typo3/cms-documentation": "^8.7.10",
		"typo3/cms-felogin": "^8.7.10",
		"typo3/cms-fluid-styled-content": "^8.7.10",
		"typo3/cms-form": "^8.7.10",
		"typo3/cms-func": "^8.7.10",
		"typo3/cms-impexp": "^8.7.10",
		"typo3/cms-info": "^8.7.10",
		"typo3/cms-info-pagetsconfig": "^8.7.10",
		"typo3/cms-rte-ckeditor": "^8.7.10",
		"typo3/cms-setup": "^8.7.10",
		"typo3/cms-sys-note": "^8.7.10",
		"typo3/cms-t3editor": "^8.7.10",
		"typo3/cms-tstemplate": "^8.7.10",
		"typo3/cms-viewpage": "^8.7.10",
		"typo3/cms-wizard-crpages": "^8.7.10",
		"typo3/cms-wizard-sortpages": "^8.7.10",
		"aoepeople/crawler": "^6.1",
		"pagemachine/typo3-composer-legacy-cli": "^1.0"
	},
    "autoload": {
        "psr-4": {
            "ProfileMedia\\UserTest\\": "public/typo3conf/ext/user_test/Classes/"
        }
    },
	"scripts":{
		"typo3-cms-scripts": [
			"typo3cms install:fixfolderstructure",
			"typo3cms install:generatepackagestates",
			"typo3cms database:updateschema",
			"typo3cms cleanup:updatereferenceindex",
			"typo3cms cache:flush"
		],
		"post-autoload-dump": [
			"@typo3-cms-scripts"
		]
	},
	"extra": {
		"typo3/cms": {
			"web-dir": "public"
		},
		"helhum/typo3-console": {
			"comment": "This option is not needed ay more for helhum/typo3-console 5.x",
			"install-extension-dummy": false
		}
	}
}

**Comment by tomasnorre** [comment] 2018-06-26 17:55
Thanks for your update @tjeske2017, I'll look into this when I'm back from vacation. 

But looks like you have found an "edge case", with the typo3/cms-* packages that we are not covering atm. Which we of course need to as this is most likely going to be the new standard. :)

**Comment by tomasnorre** [comment] 2018-07-02 16:56
@tjeske2017 

I have been looking into this again, and it looks too me like it first will be a problem in TYPO3 v9. 

This is the info in the `CliRequestHandler`

```
GeneralUtility::deprecationLog('Using cli_dispatch.phpsh as entry point for CLI commands has been marked '
. 'as deprecated and will be removed in TYPO3 v9. Please use the new CLI entrypoint via /typo3/sysext/core/bin/typo3 instead.');
```

So it should still be valid in TYPO3 8.7.x. 

I've tried to reproduce with the composer.json you pasted, and here I still have the typo3/cli_dispatch.phpsh available, and I can run the "Crawler Run Multi Process" from backend directly.

I totally agree that we need to update this, and use the commandline controller and make it available through typo3-console, but it doesn't need to be done before we move to TYPO3 9 compatibility.

If I wrong I would be happy to hear from you or anyone else, so that I can fix the problem.

**Comment by martens-web-netz-de** [comment] 2018-07-19 14:04
Hi,
we are seeing the same issue using an "typo3/cms-base-distribution" (8.7.13): The `public/typo3/cli_dispatch.phpsh` is not present. So maybe this might be a problem with the base distribution?

Is it possible to bypass this using crawler scheduler tasks via `vendor/helhum/typo3-console/typo3cms`?

**Comment by tomasnorre** [comment] 2018-07-20 05:32
I haven't tested if it works with the typo3cms, but we can check it.

**Comment by tomasnorre** [comment] 2018-11-20 07:48
This is related to #322  and we are working on this. 

I'll close this issue. Thanks for reporting it, I should have addresses this earlier and provided a fix.

**Closed by tomasnorre** 2018-11-20 07:48 UTC
Labels: 6.x, TYPO3v7, TYPO3v8, TYPO3v9, bug, feature
