### ISSUE TITLE
PhpBinaryUtility::getPhpBinary() must be of the type string

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#544] opened 2020-04-16 13:49 UTC
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Return value of AOE\Crawler\Utility\PhpBinaryUtility::getPhpBinary() must be of the type string, boolean returned | TypeError thrown in file /var/www/../web/typo3conf/ext/crawler/Classes/Utility/PhpBinaryUtility.php in line 45. Requested URL: http://mydomain.tld/typo3/index.php?route=%%2Fweb%%2Finfo%%2F&token=--AnonymizedToken--&id=40& 

- Crawler version(s): [e.g. 9.0.0]
- TYPO3 version(s): [e.g. 9.5.15]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]

The value returned is "false".

**Comment by tomasnorre** [comment] 2020-04-16 18:36
How did you get to this error, please let me know steps to reproduce.

**Comment by tomasnorre** [comment] 2020-04-16 20:41
Hi @TrueType 
I've found this issue, I think. Looks like your `phpBinary` doesn't exist. 
I've added some tests to check this, and I can reproduce your problem.

Can you please verify that it matches your problem? And that it gives you a better error with this PR.
https://github.com/AOEpeople/crawler/pull/546

Thanks

**Comment by TrueType** [comment] 2020-04-16 20:57
The values for phpBinary is default in TS "php" and phpPath is empty. I set the path to circumvent the problematic code part. The console responds to
$ php - v
So I don't know what should be problem. I will check tomorrow.

**Comment by tomasnorre** [comment] 2020-04-16 20:58
What does `which php` say?

**Comment by TrueType** [comment] 2020-04-17 07:20
I have to correct myself. I mistakenly checked with my own user on the server. Checking for the webserver user the the php binary is not set. `which php` returns nothing.

**Comment by tomasnorre** [comment] 2020-04-17 07:33
ok. So it seems like something with webserver-user and PHP is not 100% at your setup. 
Can I assist you in any way? 

Or can I close the issue?

**Comment by TrueType** [comment] 2020-04-17 08:16
Thx. Is all fine. My server configuration is quite irregular, here. Please merge the PR and close the issue. I tested your fix. Exception is handled. And - omg - we have tests.

**Closed** 2020-04-17 08:29 UTC
Labels: TYPO3v9, needs feedback
