### ISSUE TITLE
Option "Force HTTPS for all pages" not respected

### ISSUE THREAD

**Issue by t3easy** [AOEpeople/crawler#517] opened 2020-02-04 10:17 UTC
## Bug Report

**Current Behavior**
Despite that the option "Force HTTPS for all pages" is set in the config, the urls added to the queue are all http.

**Expected behavior/output**
All URLs should have https urls.

**Environment**
- Crawler version(s): 6.7.0
- TYPO3 version(s): 8.7.30
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**

**Additional context**
We are using `indexed_search`.

**Comment by tomasnorre** [comment] 2020-02-04 10:27
Thanks for the report, will check this.

**Comment by t3easy** [comment] 2020-02-04 10:32
I used the Database config and "Get Baseurl from Domainrecord" option.
Switched to "Base url" and added Url with https as a workaround.

**Comment by tomasnorre** [comment] 2020-02-04 10:40
Thanks for the additional info.. Can be important for the debugging.

**Comment by tomasnorre** [comment] 2020-03-01 17:16
Hi @t3easy 

I cannot reproduce this, can you provide me with more information. 

When setting `Force HTTPS for all pages` all my crawler entries is with `https://` when setting it to `Force HTTP for all pages` there are all with `http://` so to me it looks like it works.

**Comment by tbal** [comment] 2020-03-28 10:27
Had the same problem. Luckily this is fixed in current master thanks to PR #494 
Issue can be closed.

P.S.: Would love to see a new TER release 6.7.1 of the current master :)

**Comment by tomasnorre** [comment] 2020-03-28 11:12
Thanks for confirming. 
Will see when I get to creating a new release.

**Closed by tomasnorre** 2020-03-28 11:12 UTC
Labels: 6.x, TYPO3v8, bug, needs feedback

**Comment by tomasnorre** [comment] 2020-03-29 11:28
@tbal a 6.7.1 version is release in TER and Packagist.

**Comment by tbal** [comment] 2020-04-04 13:41
Many thanks @tomasnorre for your quick response and the new release!
