### ISSUE TITLE
FEUser GroupList not resolved recursively when crawling

### ISSUE THREAD

**Issue by lukastaferner** [AOEpeople/crawler#43] opened 2015-12-23 10:22 UTC
Unfortunately the list of groups a FE-User is member of is not resovled recursively.

It works with one level of subgroups, but if the subgroup has subgroups (and so on) different grlist entries are made the indexed_search pHash Tab (see Screenshot -> 1st entry made by manually opening the page in the browser, second row by crawler extension with same FE-Group entry).

Maybe setting the group-list in tx_crawler_hooks_tsfe->fe_feuserInit is not enough . .

**Comment by lukastaferner** [comment] 2015-12-23 10:23
![image](https://cloud.githubusercontent.com/assets/16412576/11974777/96d4926e-a967-11e5-8f68-57633975871f.png)

**Comment by tomasnorre** [comment] 2015-12-28 22:43
Thanks we will have a look after the holidays..

**Comment by tomasnorre** [comment] 2016-03-10 11:50
Hi @lukastaferner 

I cannot reproduce this with TYPO3 6.2.19 and Crawler (Master).

Can you please check again and keep me posted if this is still an issue.. 

I have tested with 4 Levels of Subgroups. Everything behaved as expected to me.

**Comment by tomasnorre** [comment] 2017-12-01 09:36
As no feedback received and I cannot reproduce, I'm closing this issue. 

If it's still an issue please reopen.

**Closed by tomasnorre** 2017-12-01 09:36 UTC
Labels: 5.x, bug, needs feedback
