### ISSUE TITLE
Cannot create crawler config if workspaces are not enabled

### ISSUE THREAD

**Issue by npostnik** [AOEpeople/crawler#90] opened 2016-05-04 07:53 UTC
It is not possible to create a 'crawler configuration' if the extension workspaces is deactivated. It would be great, if this dependancy was configurable.

**Comment by tomasnorre** [comment] 2016-05-04 10:53
Hi @npostnik 

It should be possible, but i will of course check this and get back to you. 

If it's not possible it for sure make sense to add the functionality for that.

**Comment by ses** [comment] 2016-06-13 11:27
i have the same problem :(

> Oops, an error occurred!
>
> Field sys_workspace_uid of table tx_crawler_configuration reference to foreign table sys_workspace, > but this table is not defined in TCA

**Comment by tomasnorre** [comment] 2016-06-21 11:39
Related if not duplicate of #93

**Comment by tomasnorre** [comment] 2016-06-21 11:42
Related #82

**Closed** 2016-07-19 12:51 UTC
Labels: feedback needed
