### ISSUE TITLE
[BUG] Crawler Process stops if any warning appears.

### ISSUE THREAD

**Issue by tgaertner** [AOEpeople/crawler#521] opened 2020-02-18 08:33 UTC
## Bug Report

**Current Behavior**
I created the queue via CommandController. Now I run the process via CommandCOntroller like:
`./vendor/bin/typo3 crawler:processqueue --amount 10000`

It can happen that there are warnings in the output like:
`<warning>Error: Call to a member function getStatusCode() on null</warning>`
or
`<warning>TypeError: unserialize() expects parameter 1 to be string, null given</warning>`

I think the warning can happen on try to crawl a page
- which responds with a TYPO3 Excetion
- with no SiteConfiguration (can be Footer or Imprint page if content is read by TS)
- with configured base that is not accessable because of proxy or firewall config or simply by typo
- which URL is redirected externally by a proxy or .htaccess rule

** Behavior / Problem **
If a warning appears the process stops and can not be run again, except I delete the (still marked as running) process in tx_crawler_process table.

**Expected behavior/output**
Why this can be argued as a misconfiguration crawler should output the warning(s) and continue the crawling process.

**Environment**
- Crawler version(s): 9.0.0-dev.
- TYPO3 version(s): 9.5.13
- Composer Mode: yes

**Comment by tgaertner** [comment] 2020-02-19 09:17
Thinking about this, it would be maybe also nice to have a setting (or even parameter) to control if process should stop or not. In that case it would be possible to use the crawler for FE-testing in a script.

**Comment by tomasnorre** [comment] 2020-02-24 17:44
Thanks for you input, would need to consider how this can be solve in an elegant way.

When warnings happens the user should get to know, but of course the process shouldn't stop and be blocked from running again.

**Comment by tomasnorre** [comment] 2020-04-10 06:40
@tgaertner I cannot reproduce this issue anymore with the https://github.com/AOEpeople/crawler/commit/52aa3ae8c90516df611eca7a3a978ad1411aea17 version of the crawler. 

Can you please test if you still have an issue. 

I will treat your suggestion (https://github.com/AOEpeople/crawler/issues/521#issuecomment-588116453) as a new Feature request, so could you please create a new issue for that. 

Thanks.

**Comment by tomasnorre** [comment] 2020-04-12 12:48
I'll close this issue. Please reopen if you are still having problems.

**Closed by tomasnorre** 2020-04-12 12:48 UTC
Labels: TYPO3v9, V9-Must-Have, bug, needs feedback
