### ISSUE TITLE
Module "Info" throws `findYoungestEntryForProcess() on null`

### ISSUE THREAD

**Issue by rintisch** [AOEpeople/crawler#637] opened 2020-10-21 06:14 UTC
## Bug Report

**Current Behavior**
When the command `crawler:processQueue` runs an error `Call to a member function findYoungestEntryForProcess() on null` is thrown in Module _Info_.

**Expected behavior/output**
Module _Info_ allows the inspection of the crawling process

**Environment**
- Crawler version(s): [9.1.1]
- TYPO3 version(s): [9.5.22]
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Additional context**
I run this command to warmup the cache.

Here's a screenshot
![grafik](https://user-images.githubusercontent.com/44193208/96680206-6023ea80-1375-11eb-9878-a480f1f87e25.png)

**Comment by tomasnorre** [comment] 2020-10-21 06:53
Thanks for your report @rintisch.

Did you update recently? And can you confirm if it's an issue in 9.1.0 as well.

**Comment by rintisch** [comment] 2020-10-21 07:47
@tomasnorre I updated recently and worked in 9.1.0 - sorry that I forgot this information.

**Comment by tomasnorre** [comment] 2020-10-22 05:55
No problem, just helps me debug as I know from where to start searching for the mistake. 
Thanks.

**Comment by tomasnorre** [comment] 2020-10-23 16:22
@rintisch I now had a chance to look at this, unfortunately, I cannot reproduce this with the Crawler Devbox. 

But could you please try to change the constructor in the Domain/Model/Process.php to 
```
public function __construct()
    {
        $objectManager = GeneralUtility::makeInstance(ObjectManager::class);
        $this->queueRepository = new QueueRepository();
    }
```
So that the QueueRepository created with new instead of the ObjectManager. 

I think that might work, but as I cannot reproduce this myself self it looks like it could be the problem compare to other places where I instantiate the classes. And there were changes in that regard for the Crawler. 

I have tried to add a test case to test this, but I cannot make it fail either.

**Comment by tomasnorre** [comment] 2020-10-24 06:15
I can now reproduce this: 

1. from cli or backend add Pages to the Queue
2. go to in the info module `Crawler Processes`
3. Add a new Process and the error will occur

**Comment by tomasnorre** [comment] 2020-10-24 06:20
The suggestion from https://github.com/AOEpeople/crawler/issues/637#issuecomment-715442424 doesn't change a thing. At least not in the case I have found. 

Will dig more into this during the next days. 

Can you please confirm that you can reproduce it with the steps I have written too @rintisch ?

**Comment by tomasnorre** [comment] 2020-10-24 06:36
I have found the Problem but not the solution. 

The problem is that the https://github.com/aoepeople/crawler/blob/master/Resources/Private/Templates/Backend/ProcessOverview.html#L71 is using the Process Object and fetching data directly on it from Fluid. 

The dependency injection is not working like expected any more when called from Fluid. 
I am pretty sure the problem is introduced with one of the following commits: 

https://github.com/AOEpeople/crawler/commit/ca3c80b5a42db4f3cf0a0122a74174da59b6ba40
https://github.com/AOEpeople/crawler/commit/b43fe227a5e790155217faed1a9f545155c89cf2

**Comment by tomasnorre** [comment] 2020-10-24 06:58
I will need to change a lot of calls where the QueueRepository and ProcessRepository are used to get this fixed.

Will let you know when I have a fix for this to test.

**Comment by tomasnorre** [comment] 2020-10-24 17:46
@rintisch could you please test this PR? And let me know if that fixes your problem. 

Thanks.

**Comment by rintisch** [comment] 2020-10-26 06:46
@tomasnorre 

**First:** Thanks for digging into it!

My steps are always the following:

- from backend add Pages to the Queue with the module _Scheduler_ (command = `crawler:buildQueue ... --mode=queue`)
- start crawler from module _Scheduler_ (command = `crawler:processQueue`)
- go to in the module _Info_ → _Crawler Processes_
- see error

With the PR it does not throw an error any longer but I get this error:
![grafik](https://user-images.githubusercontent.com/44193208/97140705-81ae1900-175d-11eb-835d-d52d383ca4eb.png)
Nevertheless the process reduces the amount of pending entries. But at the end it the pages have no entries (and my cache redis storage did not grow, so there was really no processing)

So I would say: The problem this issue was about is solved but in reality another problem exists: The queue is not processed!?

**Comment by tomasnorre** [comment] 2020-10-26 07:13
ok. I'll dig a little more. 
Thanks for updating me.

**Comment by tomasnorre** [comment] 2020-10-26 16:02
I can reproduce the second issue too. As it's tightly related to the fix, I'll keep this handle as one issue as I think I introduced during the fix.

**Comment by tomasnorre** [comment] 2020-10-26 17:14
@rintisch Can you please test branch issue/637 again, I think I have solved both problems now.

**Comment by rintisch** [comment] 2020-10-27 05:42
@tomasnorre The crawler does not throw an error, but unfortunately no cache is created. 
![grafik](https://user-images.githubusercontent.com/44193208/97261593-6a376480-181f-11eb-801c-909d92e4989b.png)
The processing time is much too short (5s), normally crawling those 76 pages needs a few seconds...

**Comment by tomasnorre** [comment] 2020-10-27 05:49
ok. That's part I must honestly say I haven't proved, as I believed in the process state. Will check.

**Comment by tomasnorre** [comment] 2020-10-27 16:57
@rintisch Which cache tables do you prove after the process is done?

**Comment by rintisch** [comment] 2020-10-28 06:45
Hm, I watched the memory usage of my redis container. When cache is build up it need a few MB more memory - that was my indicator. I will tomorror have a look at it.

**Comment by tomasnorre** [comment] 2020-10-28 07:08
Thanks. The crawler has no direct influence on Redis, the Crawler do nothing but visiting the page. So i'm pretty sure that this is not an Crawler issue, if an issue. I'll keep this open till I have your feedback. I could be wrong :)

**Comment by rintisch** [comment] 2020-10-29 06:37
I tested now with once more, this time with caching in DB to see directly what happens: 
With version 9.1.0 I get the following:
![grafik](https://user-images.githubusercontent.com/44193208/97532103-ebc0fb00-19b5-11eb-96e2-6049ecb4b095.png)
→ Cache in DB gets filled (checked with phpMyAdmin)

With 9.1.2-dev:
Same times as posted above, cache in DB stays empty.

So I checked the Crawler log:
![grafik](https://user-images.githubusercontent.com/44193208/97533284-3d6a8500-19b8-11eb-8437-47fab1670932.png)

At the end I figured out: I get this error when adding as `usergroup` to the crawler and it doesn't matter whether the page itself is access restricted or not.

**Comment by tomasnorre** [comment] 2020-10-29 06:52
OK. Now I think we are approaching a new issue, would you mind creating a new one with the latest information?

**Comment by rintisch** [comment] 2020-10-29 07:04
I created the issue #643 - I think you can close this ticket.

**Comment by tomasnorre** [comment] 2020-10-29 07:07
Thanks, will have this merged before closing it. Thanks for you fast feedback makes it a lot easier to provide fixes.

**Comment by rintisch** [comment] 2020-10-29 07:17
Thank you for digging so much into it!

**Closed** 2020-10-30 05:25 UTC
Labels: Bug, Priority 1, TYPO3v10, TYPO3v9, needs feedback
