### ISSUE TITLE
external files with spaces, umlauts, etc are not queued by indexer

### ISSUE THREAD

**Issue by TrueType** [AOEpeople/crawler#578] opened 2020-05-21 11:05 UTC
TYPO3v9.5.17 and EXT:crawler 9.0.1
systemLocale = de_DE.UTF-8

Indexing a page creates new queue entries for files found therein. I lately had problems  - may still have - with spaces in file names, now I have problems with non-ASCII characters like the german sharp "s", which is "ß". 

It just misses such a file and creates no entrie in the queue. All other files of same type are fine. Changing the filename to "ss" the problem goes away. So the case is clear.

**Comment by tomasnorre** [comment] 2020-05-21 15:12
I would need to add some functional tests around the file-crawling in general, there are currently some issues with this.

**Comment by tomasnorre** [comment] 2020-05-21 15:26
In my setup the filenames are converted to e.g. ss instead of ß. I know that's not necessarily a solution, as many will use localized filenames regardless of my setup and what I prefer ;)

**Comment by tomasnorre** [comment] 2020-05-27 18:46
I have found the problem regarding the non-ASCII chars in filenames.

Example: 
I have file `german-buchstaben-ßöü.jpg` that will the `indexed_search` indexer in `extractLinks()` be converted with `htmlspecialchars_decode()` which will result in a file called `german-buchstaben-%C3%9F%C3%B6%C3%BC.jpg`

When it then later check if the file exists it doesn't as it doesn't convert filename back, so this looks more like a core (indexed_search) issue than a crawler issue to me. The question is if that's intended by the core, I cannot answer that, but perhaps @bmack can. I personally would always suggest my clients/users to not use non-ASCII filenames, regardless of system. But I know it's not always that straight forward.

TYPO3 9 LTS
https://github.com/TYPO3/TYPO3.CMS/blob/9.5/typo3/sysext/indexed_search/Classes/Indexer.php#L829

TYPO3 10 LTS
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/indexed_search/Classes/Indexer.php#L574

**Comment by tomasnorre** [comment] 2020-06-02 15:53
This is strange.. I haven't done anything, that I am aware of at least. Was working on some other issue trying to reproduce that, and now my german lettered files are indexed as well. 

![Screenshot from 2020-06-02 17:51:23](https://user-images.githubusercontent.com/1212481/83541440-f2783e80-a4f9-11ea-9d58-452916e5392c.png)

**Comment by TrueType** [comment] 2020-06-02 15:55
Haha. Real magic. But a good sign of course.

**Comment by tomasnorre** [comment] 2020-06-02 16:00
Yeah, but would like to understand what the difference is. I did a composer update, so I'm on dev-master for the crawler now. Looks like it was locked on an older branch for another feature.

But you are on 9.0.1 too right?? 

And there aren't' many commits since then and really none that so influence this. 
Some composer scripting, some typos, rename of the devbox. Should all be non-related to the issue you're having. 

And with the reference above to the core it should as I read it, not work.

```
* e324a3a - [TASK] Correct spelling of commands (5 days ago) <Chris Müller>
* eaa3f4a - Fix typos in ext_conf_template.txt (5 days ago) <Chris Müller>
* 2dbe68f - [TASK] Rename crawler-typo3v9 to crawler-devbox (10 days ago) <Tomas Norre Mikkelsen>
* 64b7dc5 - [TASK] Add tests for SubProcessExecutionStrategy (10 days ago) <Tomas Norre Mikkelsen>
* 744c705 - [TASK] Add rector to scripts + sorting (3 weeks ago) <Tomas Norre Mikkelsen>
``

**Comment by TrueType** [comment] 2020-06-04 08:49
@tomasnorre hi, customer complains about missing files (have spaces). So I will work on the subject again. First thing is i will composer update from v9.5.17 to v9.5.18 and check. As we probably both figure the indexing of the files cannot be a matter of EXT:crawler but of EXT:indexed_search. As the indexing is done solely there. Everything else would be rare.

**Comment by TrueType** [comment] 2020-06-04 15:13
Ok. Changing this line - https://github.com/TYPO3-CMS/indexed_search/blob/master/Classes/Indexer.php#L630 -
```
   'href' => $tagAttributes[0]['href'],
   'localPath' => $this->createLocalPath(urldecode($tagAttributes[0]['href']))
```
gets it going. The htmlParser delivers all URIs urlencoded. As the URI is set into 'localPath' it enters another world. Local storage. Non-HTTP. And should be urldecoded(). 

That is of course all EXT:indexed_search ..

**Comment by TrueType** [comment] 2020-06-04 15:54
created a forge issue - https://forge.typo3.org/issues/91586
@bmack perhaps you can kick this into gerrit. should not have any side effects. besides the positive ones. thx

**Comment by jonaseberle** [comment] 2020-06-04 18:29
I created a patch from that: https://review.typo3.org/c/Packages/TYPO3.CMS/+/64772 - it would be great if you could test and verify it.

**Comment by tomasnorre** [comment] 2020-06-05 05:53
Thanks, for taking care. I'll close this issue as it's not caused by the crawler.

**Closed by tomasnorre** 2020-06-05 05:53 UTC
Labels: 3rd party ext, Bug, Priority 2, TYPO3v9, needs feedback
