### ISSUE TITLE
Not see the context menue for the queue

### ISSUE THREAD

**Issue by developerroom** [AOEpeople/crawler#442] opened 2019-08-28 09:20 UTC
Not see the context menue for the queue:
TYPO3 8.7.27

**Comment by tomasnorre** [comment] 2019-08-29 06:29
Can you please elaborate, a little more. 

What don't you see? 
How to reproduce?
What is expected behaviour?
Which Crawler version?

If I'm getting you correct, this is the reason.
https://github.com/AOEpeople/crawler/blob/2e37c2582fa7f3adf8eadb01f0c2092aa2f0a419/Classes/Utility/BackendUtility.php#L63

We disabled the ClickMenu for TYPO3 < 8.6

**Comment by tomasnorre** [comment] 2020-04-12 12:49
Will close this issue as there has been no feedback. 
Please reopen if it's still an issue.

**Closed by tomasnorre** 2020-04-12 12:49 UTC
Labels: needs feedback
