### ISSUE TITLE
Error sys_workspace_uid of table tx_crawler_configuration

### ISSUE THREAD

**Issue by ses** [AOEpeople/crawler#93] opened 2016-06-03 10:11 UTC
the error in the BE TYPO3 7.6.9

> #1439569743: Field sys_workspace_uid of table tx_crawler_configuration reference to foreign table sys_workspace, but this table is not defined in TCA (More information)
> 
> UnexpectedValueException thrown in file
> /html/indoorgolf/typo3_src-7.6.9/typo3/sysext/backend/Classes/Form/FormDataProvider/AbstractItemProvider.php in line 422.

**Comment by tomasnorre** [comment] 2016-06-07 07:37
Hi @ses 

Thanks for reporting. Will have a look soonish.

**Comment by tomasnorre** [comment] 2016-06-19 16:09
This is related to forge ticket: https://forge.typo3.org/issues/70052

Was suppose to be solved, but we encountered some issue earlier ehen trying to enabled it again, we would need to look into this again.

From TCA configuration.
 // displayCond's are broken with 7.5, so disable workspace support for now (#70052)
        /*'sys_workspace_uid' => Array (
            'exclude' => 1,
            'label' => 'LLL:EXT:crawler/locallang_db.xml:tx_crawler_configuration.sys_workspace_uid',
            'displayCond' => 'EXT:workspaces:LOADED:true',
            'config' => Array (
                'type' => 'select',
                'items' => Array (
                    Array('LLL:EXT:lang/locallang_misc.xml:shortcut_onlineWS', 0),
                ),
                'size' => 1,
                'maxitems' => 1,
                'exclusiveKeys' => '-1,0',
                'foreign_table' => 'sys_workspace'
            )
        ),*/

**Comment by tomasnorre** [comment] 2016-06-21 11:40
Related if not duplicate of #90

**Comment by tomasnorre** [comment] 2016-06-21 11:41
Related #82

**Closed** 2016-07-19 12:51 UTC
Labels: feedback needed
