### ISSUE TITLE
Use crawler V9 in Typo3 10 with configured frontend user groups results in Error

### ISSUE THREAD

**Issue by Wh0l3** [AOEpeople/crawler#617] opened 2020-08-13 15:03 UTC
When I try to crawl a page in the frontend which is only accessible with a login (a.k.a fe_group), and set this frontend_group in the crawler config, it results in an error.

**Current Behavior**
Error output:
Thu, 13 Aug 2020 11:34:05 +0000 [CRITICAL] request="14797fa2f4b5d" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Core\Context\UserAspect::__construct() must be an instance of TYPO3\CMS\Core\Authentication\AbstractUserAuthentication or null, instance of stdClass given, called in /var/www/html/web/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3423 | TypeError thrown in file /var/www/html/web/typo3/sysext/core/Classes/Context/UserAspect.php in line 55. Requested URL: http://mysite.com/protectedsite - {"TYPO3_MODE":"FE","exception":{}}

**Expected behavior/output**

**Environment**
- Crawler version(s): ^9.0
- TYPO3 version(s): ^10.4
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
AOE\Crawler\Middleware\FrontendUserAuthenticator
In the function setAspect - try to cast the variable $frontendUser to an AbstractUserAuthentication.
I tried to set $frontendUser to null, as it only needs de groups from $grList. This did not work for me.

**Comment by tomasnorre** [comment] 2020-08-20 17:53
I can confirm this problem. I'll see what I can do to fix this.

**Comment by tomasnorre** [comment] 2020-08-20 18:25
@Wh0l3  I think i found a solution. Could you please verify this branch? 
https://github.com/AOEpeople/crawler/tree/issue/617

**Comment by Wh0l3** [comment] 2020-09-02 09:09
I took some code from the core-extension "adminpanel"... and that seemed to do the job

As I was not able to pull the issue correctly, here is the code i got:

Classes/Middleware/FrontendUserAuthentication.php, line 92-108: 

if ($grList) {
            $frontendUser = $request->getAttribute('frontend.user');
            $frontendUser->user[$frontendUser->usergroup_column] = '0,-2,' . $grList; //'0,-2,' . $grList;
            $frontendUser->user['uid'] = PHP_INT_MAX;

            // we have to set the fe user group to the user aspect since indexed_search only reads the user aspect
            // to get the groups. otherwise groups are ignored during indexing.
            // we need to add the groups 0, and -2 too, like the getGroupIds getter does.
            $this->context->setAspect(
                'frontend.user',
                GeneralUtility::makeInstance(
                    UserAspect::class,
                    $frontendUser,
                    explode(',', '0,-2,'.$grList)
                )
            );
        }

**Comment by tomasnorre** [comment] 2020-09-02 10:34
Thanks, I'll be checking this out, beginning next week. Off for the next couple of days.

**Comment by tomasnorre** [comment] 2020-09-09 16:25
@Wh0l3 I can confirm that it's working like intended now, can you please confirm that the PR is working? 
Thanks

**Comment by Wh0l3** [comment] 2020-09-10 06:52
@tomasnorre Downloaded and testet. It works like intended now, I got an OK status on a groups-protected page

**Comment by tomasnorre** [comment] 2020-09-10 07:09
@Wh0l3 Super, happy to hear. Do you mind doing the Code Review too? Then I'll have this merged and added in the next release.

**Comment by tomasnorre** [comment] 2020-09-10 07:19
Thanks a lot @Wh0l3

**Closed** 2020-09-10 07:19 UTC
Labels: Bug, Priority 1, TYPO3v10
