### ISSUE TITLE
[BUG] Can not create schedular tasks after installing crawler

### ISSUE THREAD

**Issue by r3h6** [AOEpeople/crawler#279] opened 2018-04-05 13:28 UTC
After clicking on the plus-button for creating a new schedular task no backend form is displayed.
TYPO3 8.7 with composer.

**Comment by r3h6** [comment] 2018-04-19 12:11
After clicking on the "Add task" Button...
![a](https://user-images.githubusercontent.com/4550541/38990575-22aa1aec-43db-11e8-9bc5-ca6219ba40ce.png)

... I expect to get the form for creating a new task.
![b](https://user-images.githubusercontent.com/4550541/38990576-22dba3a0-43db-11e8-90f1-0a13ebf4a3e3.png)

... but after installing the "crawler" extension, I get this (note that there is a "Save" Button but no form):
![c](https://user-images.githubusercontent.com/4550541/38990577-230e5458-43db-11e8-9a34-3ad87738b49a.png)

**Comment by tomasnorre** [comment] 2018-04-19 13:32
Sorry but the screenshots doesn't help me a lot, I knew the steps, they don't bring me more information.. 

Do you get other errors than "no tasks defined yet" ?

**Comment by r3h6** [comment] 2018-04-20 13:09
The problem is in CrawlerQueueTaskAdditionalFieldProvider::getSelectedState (Line 149):
`$arraySize = count($configurationArray);`

$configurationArray is NULL...

**Comment by tomasnorre** [comment] 2018-04-23 05:03
@r3h6 Thanks for your PR.. Will have a look tomorrow.

As I cannot reproduce the Problem, I'll have to dig into it, before I merge the PR. 

I'll get back to you if I have any questions.

**Comment by tomasnorre** [comment] 2018-04-27 19:08
@r3h6 Can you please test if #284 fixes your problem. 

From the code, the $configurationArray cannot be empty anymore as I read it.. 
If it's working for you we have to fixes within one PR. 

If it is not working I'll look into to your PR again.

**Comment by r3h6** [comment] 2018-05-01 12:00
Issue "issue/190" doesn't solve the problem.

**Comment by tomasnorre** [comment] 2018-05-01 17:03
ok.. Thanks for letting us know. I'll take a look at your PR once again.

**Comment by tomasnorre** [comment] 2018-05-03 13:18
@r3h6 Can you please test with current master, we have added some fixes that should solve the problem.

**Comment by r3h6** [comment] 2018-05-07 11:59
With current master I get following exception:

Argument 1 passed to AOE\Crawler\Task\CrawlerQueueTaskAdditionalFieldProvider::getSelectedState() must be of the type array, null given, called in /var/www/web/typo3conf/ext/crawler/Classes/Task/CrawlerQueueTaskAdditionalFieldProvider.php on line 105 


[TYPO3 Exception.pdf](https://github.com/AOEpeople/crawler/files/1979738/TYPO3.Exception.pdf)

**Comment by tomasnorre** [comment] 2018-05-07 18:45
@r3h6 Can you please check master with this commit cherry-picked. 
https://github.com/AOEpeople/crawler/commit/c2524b0cceaeb013b79a17dd3ddd7ad198c5c8e5

This at least solves your latest problem as described in 
https://github.com/AOEpeople/crawler/issues/279#issuecomment-387042798

**Comment by r3h6** [comment] 2018-05-08 14:28
Master with cherry-picked c2524b0 solves the problems described here. This issue can be closed when commit c2524b0 is applied.

**Comment by tomasnorre** [comment] 2018-05-08 16:49
Thanks for getting back to us. Will make sure we get a release done asap.

**Comment by tomasnorre** [comment] 2018-05-09 04:56
Resolved with #296

**Closed by tomasnorre** 2018-05-09 04:56 UTC
Labels: in progress
